from fastapi import APIRouter, Depends, HTTPException, Query
from pydantic import BaseModel
from sqlalchemy.orm import Session

from app.auth.dependencies import get_current_user, require_role
from app.database import get_db
from app.models.notification import Notification, NotificationStatus, NotificationType, Severity, SimulatedAlert
from app.models.user import Role, User
from app.services.notification_service import notify_once, sweep_maintenance_due

router = APIRouter(prefix="/api/v1", tags=["notifications"])


class NotificationResponse(BaseModel):
    id: str
    notif_type: str
    severity: str
    target_role: str
    entity_type: str
    entity_id: str
    message: str
    status: str
    created_at: str | None = None

    model_config = {"from_attributes": False}


class SimulatedAlertResponse(BaseModel):
    id: str
    channel: str
    recipient: str
    subject: str
    body: str
    entity_type: str
    entity_id: str
    label: str

    model_config = {"from_attributes": False}


class AdvisoryCreate(BaseModel):
    message: str
    target_role: str = "EMERGENCY_COORDINATOR"
    severity: Severity = Severity.WARNING


@router.post("/notifications", response_model=NotificationResponse, status_code=201)
def create_advisory(
    body: AdvisoryCreate,
    db: Session = Depends(get_db),
    user: User = Depends(require_role(Role.ADMIN, Role.EXPEDITION_LEADER, Role.EMERGENCY_COORDINATOR)),
):
    """Human/AI advisory channel. Only AI_ADVISORY is creatable here —
    all other types are system-generated by the rules engine."""
    from app.models.audit import AuditAction, AuditEvent

    n = notify_once(db, NotificationType.AI_ADVISORY, body.severity, body.target_role, "Advisory", f"ai-{user.id}", f"[AI draft — acknowledge before acting] {body.message}")
    if n is None:
        raise HTTPException(status_code=409, detail="identical unread advisory already exists")
    db.add(AuditEvent(actor_id=user.id, action=AuditAction.CREATE, entity_type="Notification", entity_id=n.id, new_value="AI_ADVISORY", source="SYNTHETIC_DEMO"))
    db.commit()
    db.refresh(n)
    return _out(n)


def _out(n: Notification) -> NotificationResponse:
    sval = lambda s: s.value if hasattr(s, "value") else str(s)
    return NotificationResponse(
        id=n.id, notif_type=sval(n.notif_type), severity=sval(n.severity), target_role=n.target_role,
        entity_type=n.entity_type, entity_id=n.entity_id, message=n.message or "",
        status=sval(n.status), created_at=str(n.created_at) if n.created_at else None,
    )


@router.get("/notifications", response_model=list[NotificationResponse])
def list_all(db: Session = Depends(get_db), _: User = Depends(get_current_user), status: str | None = Query(default=None), notif_type: str | None = Query(default=None)):
    sweep_maintenance_due(db)  # lazy rule: due-soon assets surface here even with no event traffic
    q = db.query(Notification).order_by(Notification.created_at.desc())
    if status:
        q = q.filter(Notification.status == status)
    if notif_type:
        q = q.filter(Notification.notif_type == notif_type)
    return [_out(n) for n in q.all()]


def _set_status(db: Session, nid: str, to: NotificationStatus, user: User) -> NotificationResponse:
    from app.models.audit import AuditAction, AuditEvent

    n = db.query(Notification).filter(Notification.id == nid).first()
    if not n:
        raise HTTPException(status_code=404, detail="notification not found")
    n.status = to
    db.add(AuditEvent(actor_id=user.id, action=AuditAction.APPROVE, entity_type="Notification", entity_id=n.id, new_value=to.value, source="SYNTHETIC_DEMO"))
    db.commit()
    db.refresh(n)
    return _out(n)


@router.post("/notifications/{nid}/read", response_model=NotificationResponse)
def mark_read(nid: str, db: Session = Depends(get_db), user: User = Depends(get_current_user)):
    return _set_status(db, nid, NotificationStatus.READ, user)


@router.post("/notifications/{nid}/acknowledge", response_model=NotificationResponse)
def acknowledge(nid: str, db: Session = Depends(get_db), user: User = Depends(get_current_user)):
    return _set_status(db, nid, NotificationStatus.ACKNOWLEDGED, user)


@router.get("/alerts/simulated", response_model=list[SimulatedAlertResponse])
def simulated(db: Session = Depends(get_db), _: User = Depends(get_current_user)):
    rows = db.query(SimulatedAlert).order_by(SimulatedAlert.created_at.desc()).all()
    return [SimulatedAlertResponse(id=r.id, channel=r.channel, recipient=r.recipient, subject=r.subject, body=r.body or "", entity_type=r.entity_type, entity_id=r.entity_id, label=r.label) for r in rows]
